Document: raqetclient
Title: Debian raqetclient Manual
Author: <insert document author here>
Abstract: This manual describes what raqetclient is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/raqetclient/raqetclient.sgml.gz

Format: postscript
Files: /usr/share/doc/raqetclient/raqetclient.ps.gz

Format: text
Files: /usr/share/doc/raqetclient/raqetclient.text.gz

Format: HTML
Index: /usr/share/doc/raqetclient/html/index.html
Files: /usr/share/doc/raqetclient/html/*.html
